### PR TITLE
Don't show category list if only one is available

### PR DESCRIPTION
**Pull request by davefx**
Change made for not showing category list if there's no categories available.
If there's only one category available, don't show it and mark it by default.

### CODE REVIEW

**Comment by dansod** [comment]
Hi there @davefx!
Sorry but I haven´t had the time to work with this repo in the last couple of months. I also noticed it´s out of date. I am about to do a new start and work more properly with this git and i will look at your request. Thanks for your input!

**Comment by dansod** [comment]
Hi again, i was testing this one. It´s a good feature but i cannot get it to work, it might be that the repo here on Github was out of date, i dont know but here is my issue.

If I have only one category its not showing up as an option and that is working fine (really good), but when the user subscribe it wont get the hidden category attached. 

I also find a missing '(' at line 785.

**Comment by davefx** [comment]
There were some errors in the patch. Now it should work OK.

**Comment by dansod** [comment]
Thanks for your contribution!

**Pull request merged**
